"""Initial migration

Revision ID: 94b856689659
Revises: 
Create Date: 2025-08-12 21:15:28.492441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94b856689659'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'deleted', name='productstatus'), nullable=False),
    sa.Column('type_of_sim', sa.Enum('SIM', 'eSIM', name='simtype'), nullable=False),
    sa.Column('operator_code', sa.Enum('DTAC', 'ais', 'JOYTEL', name='operatorcode'), nullable=False),
    sa.Column('vendor_code', sa.Enum('DTAC', 'FRAGRANT', 'COMMBITZ', 'KANGO', name='vendorcode'), nullable=False),
    sa.Column('purchase_type', sa.Enum('API Purchase', 'Manual Purchase', 'Only Stock', name='purchasetype'), nullable=False),
    sa.Column('sku_type', sa.Enum('Base', 'Datapack', 'Base + Datapack', name='skutype'), nullable=False),
    sa.Column('data_type', sa.Enum('Fixed Data', 'Daily Data', name='datatype'), nullable=False),
    sa.Column('hotspot', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_product_code'), 'product', ['product_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_product_product_code'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
